///scr_get_equipment_mapping();
// Loads static variable mapping for equipment stat index;
_eq_script = 0;
_eq_active = 20;
_eq_input_down = 1;
_eq_input_up = 19;
_eq_progress_time = 2;
_eq_image_index = 3;
_eq_sprite = 4;
_eq_collision_sprite = 5;
_eq_particle_sprite = 6;
_eq_hit_pause_time = 7;
_eq_icon_index = 8;
_eq_executed = 9;
_eq_execution_time = 10;
_eq_height = 11;
_eq_time = 12;
_eq_combo_time = 13;
_eq_combo_ready = 14;
_eq_damage = 15;
_eq_stun_time = 16;
_eq_knockback = 17;
_eq_active_movement_modifier = 18;
